export default {
  GET_PROGRAMS: 'GET_PROGRAMS',
  GET_SINGLE_PROGRAM: 'GET_SINGLE_PROGRAM',
  ADD_PROGRAM: 'ADD_PROGRAM',
  REMOVE_PROGRAM: 'REMOVE_PROGRAM',
  UPDATE_PROGRAM: 'UPDATE_PROGRAM',
  PROGRAM_IS_LOADING: 'PROGRAM_IS_LOADING',
  PROGRAM_HAS_ERROR: 'PROGRAM_HAS_ERROR',

  GET_EXERCISES: 'GET_EXERCISES',
  EXERCISES_IS_LOADING: 'EXERCISES_IS_LOADING',

  GET_WORKOUTS: 'GET_WORKOUTS',
  ADD_WORKOUT: 'ADD_WORKOUT',
  REMOVE_WORKOUT: 'REMOVE_WORKOUT',
  WORKOUT_IS_LOADING: 'WORKOUT_IS_LOADING',
  WORKOUT_HAS_ERROR: 'WORKOUT_HAS_ERROR'
}