export default {
  GET_PROGRAMS: 'GET_PROGRAMS',
  ADD_PROGRAM: 'ADD_PROGRAM',
  REMOVE_PROGRAM: 'REMOVE_PROGRAM',
  UPDATE_PROGRAM: 'UPDATE_PROGRAM',
  FETCHING_PROGRAMS: 'FETCHING_PROGRAMS',
  PROGRAM_IS_LOADING: 'PROGRAM_IS_LOADING',
  PROGRAM_HAS_ERROR: 'PROGRAM_HAS_ERROR',

  GET_EXERCISES: 'GET_EXERCISES'
}